# Generated by Django 3.0 on 2020-01-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='product',
        ),
    ]
