# Generated by Django 3.0 on 2020-01-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0002_remove_coment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coments.Coment'),
        ),
    ]
