# Generated by Django 3.0 on 2020-01-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='bloop'),
            preserve_default=False,
        ),
    ]
