# Generated by Django 3.0 on 2020-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20200118_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(),
        ),
    ]
