# Generated by Django 3.0 on 2020-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20200118_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors'),
        ),
    ]
