# Generated by Django 3.0 on 2020-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200125_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
